### ISSUE TITLE
数据treeData不能动态设置

### ISSUE THREAD

**Issue by zhangjiwei14** [lazyboyl/iview-select-tree#3]
初始化treeData的数据可以显示，但是通过其他事件修改treeData后，不显示其修改内容

**Comment by 2419930554** [comment]
这个问题好像是的，不过也能解决，用if判断就行了

**Comment by lazyboyl** [comment]
> 初始化treeData的数据可以显示，但是通过其他事件修改treeData后，不显示其修改内容

已经增加此项功能，可以更新到1.0.9版本，欢迎提出你们的issue
