### ISSUE TITLE
v-model双向绑定有问题

### ISSUE THREAD

**Issue by GyPsyEyes** [lazyboyl/iview-select-tree#6]
![image](https://user-images.githubusercontent.com/21237260/99610044-03871e80-2a4c-11eb-923f-bc25c11aed84.png)
点击测试按钮，赋值为【广州】，显示效果如下。
![image](https://user-images.githubusercontent.com/21237260/99610138-33362680-2a4c-11eb-9a65-5a969e0d92f0.png)

**Comment by lazyboyl** [comment]
升级到1.0.11即可解决该问题
