### ISSUE TITLE
数据回写问题

### ISSUE THREAD

**Issue by xyf15208235102** [lazyboyl/iview-select-tree#7]
<selectTree
      :multiple="true"
      v-model="val"
      :showQuery="true"
      :treeData="treeData"
      @on-select-change="selectChange"
    ></selectTree>

直接在data里声明val:[123]能正常回写
如果在mounted里this.val = [123]  这样回写不了
请问是什么原因呢

**Comment by lazyboyl** [comment]
升级到1.0.11版本即可
