### ISSUE TITLE
多选数据删除后，树结构未及时更新。依旧处于选中状态

### ISSUE THREAD

**Issue by ANTHAK** [lazyboyl/iview-select-tree#8]
![image](https://user-images.githubusercontent.com/25068848/100866746-141ba800-34d4-11eb-80c7-65b4d2819a6c.png)

**Comment by lazyboyl** [comment]
无法重新此问题，iview 的版本不能高于3.4.x版本

**Comment by ANTHAK** [comment]
好的 麻烦了

**Comment by ANTHAK** [comment]
目前我使用的是 iView 4.0
